Repository Dayana-World/Dayana-Python-Lab, pull requests merged in 2022-10, with the labels that each got.

#11 add simple calculator and temperature convertor to dayana python lab
  Dayana python lab/0_Education/0_education_play_ground/00_code_lake/calculator(Simple version).py
  Dayana python lab/0_Education/0_education_play_ground/00_code_lake/temperature convertor.py
Labels: good first issue

#43 update
  Dayana python lab/0_playground/0_train_playground/hossein_choopani/SA for TSP.py
  Dayana python lab/0_playground/0_train_playground/mohammad_reza_rokni/amazon_price_tracker.py
  Dayana python lab/1_data_lake/1_light_weight_data/b52_dataset.csv
Labels: enhancement

#45 level 5
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/REGuide.txt
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/level_1.py
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/level_2.py
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/level_3.py
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/level_5.py
  Dayana python lab/2_game/1_hipy_game/part 11 - R.E/level_6.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/SPGuide.txt
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_1.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_2.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_3.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_4.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_5.py
  Dayana python lab/2_game/1_hipy_game/part 22 -  S.P/lvl_6.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/UPGuide.txt
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_1.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_2.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_3.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_4.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_5.py
  Dayana python lab/2_game/1_hipy_game/part 33 - U.P/lvl_6.py
  Dayana python lab/2_game/1_hipy_game/part 44 - H.R/part4 - guide.txt
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/guide.txt
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level1_a_bug_can_be_a_bad_usage_of_syntax.py
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level2_i_forgot_build_file_first.py
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level3_proxy_wont_work_bug.py
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level4_help_me_to_connect.py
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level5_finde_element_bug.py
  Dayana python lab/2_game/1_hipy_game/part 5 - H.B/level6_are_you_ok.py
Labels: bug, documentation, enhancement

#46 p6
  Dayana python lab/2_game/1_hipy_game/part 6/guide.txt
Labels: documentation, enhancement
